/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.covid.forms;

import com.covid.classes.*;
import com.covid.classes.StatusClass;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.*;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.text.SimpleDateFormat;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.io.File;

/**
 *
 * @author Aditya
 */
public class RegisterForVaccine extends javax.swing.JFrame {
    java.util.Date date = new java.util.Date();
    long ltime = date.getTime()+8*24*60*60*1000;
    java.util.Date date1 = new java.util.Date(ltime);
    Calendar c = Calendar.getInstance();
    String pid = StatusClass.id;
    DBClass db = new DBClass();
    File f;

    /**
     * Creates new form RegisterForVaccine
     */
    public RegisterForVaccine() {
        initComponents();
        jDateChooser1.setMaxSelectableDate(date1);
        jDateChooser1.setMinSelectableDate(date);
        ResultSet rs1 = db.getData("select * from regisetrforvaccine where pid='" + pid + "'");
        try {
            if (rs1.next()) {
                Cmbid1.setSelectedItem(rs1.getString(2));
                IdNo.setText(rs1.getString(3));
                Name.setText(rs1.getString(5));
                Gender.setSelectedItem(rs1.getString(6));
                jDateChooser1.setDate(db.setDate1(rs1, 9));
                BYear.setText(rs1.getString(9));
                byte[] img = rs1.getBytes(4);
                Image imgaImage = getToolkit().createImage(img);
                ImageIcon icon = new ImageIcon(imgaImage);
                imgLbl.setIcon(icon);
                time.setSelectedItem(rs1.getString(12));
                Vtype.setSelectedItem(rs1.getString(11));
                Center.setSelectedItem(rs1.getString(10));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForVaccine.class.getName()).log(Level.SEVERE, null, ex);
        }
        db.fillCombo(Center, "select name from centertbl where covaxin >= 10 and covishield >= 10");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdNo = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        BYear = new javax.swing.JTextField();
        imgLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Vtype = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        Cmbid1 = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Center = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 0, 102));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 153, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificate (3).png"))); // NOI18N
        jLabel6.setText("Vaccination Registration");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(19, 19, 19))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        kGradientPanel1.setkGradientFocus(700);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-card (1).png"))); // NOI18N
        jLabel1.setText("Photo ID Proof");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-card (4).png"))); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-card (1).png"))); // NOI18N
        jLabel3.setText("Photo ID Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gender.png"))); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/birthday-cake.png"))); // NOI18N
        jLabel5.setText("Year of Birth");

        IdNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IdNo.setForeground(new java.awt.Color(102, 102, 255));

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(102, 102, 255));

        BYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BYear.setForeground(new java.awt.Color(102, 102, 255));

        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-card.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine.png"))); // NOI18N
        jLabel8.setText("Vaccine");

        Vtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Vtype.setForeground(new java.awt.Color(102, 102, 255));
        Vtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Covaxin", "Covishield" }));
        Vtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VtypeItemStateChanged(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(14, 109, 173));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
        jButton3.setText("CHOOSE");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Cmbid1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cmbid1.setForeground(new java.awt.Color(102, 102, 255));
        Cmbid1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adharcard", "Pancard", "VoterId" }));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(102, 102, 255));
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        jButton4.setBackground(new java.awt.Color(14, 109, 173));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location.png"))); // NOI18N
        jLabel10.setText("Select Center");

        Center.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Center.setForeground(new java.awt.Color(102, 102, 255));
        Center.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adharcard", "Pancard", "VoterId" }));
        Center.setSelectedIndex(-1);
        Center.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CenterItemStateChanged(evt);
            }
        });
        Center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenterActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jLabel11.setText("Select Date");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock.png"))); // NOI18N
        jLabel12.setText("Select Time");

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(102, 102, 255));
        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8-10", "11-1", "1-5" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        jLabel13.setText("Select ID Image");

        jDateChooser1.setForeground(new java.awt.Color(255, 0, 0));
        jDateChooser1.setMaxSelectableDate(new java.util.Date(253370797266000L));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(BYear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cmbid1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel13)))
                                    .addComponent(jLabel10))
                                .addGap(9, 9, 9)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Center, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Vtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGap(316, 316, 316))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cmbid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 150, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel11))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setDialogTitle("Choose Image");
        int a = jf.showOpenDialog(this);
        
        if (a == JFileChooser.APPROVE_OPTION) {
            f = jf.getSelectedFile();
            ImageUtiltiy.setLabelImage(f, imgLbl);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String idtype = (String) Cmbid1.getSelectedItem();
        String idno = IdNo.getText();
        String name = StatusClass.name;
        int id = 0;
        String ceter = (String) Center.getSelectedItem();
//        ceter = StatusClass.centername;
        String date = db.getDate1(jDateChooser1);
//        date = StatusClass.date;
        String time = (String) this.time.getSelectedItem();
        String rand = StatusClass.rand;
        //String pid = StatusClass.id;
        String gender = (String) Gender.getSelectedItem();
        String doseno = "Registered For First Dose";
        String year = BYear.getText();
        String vaccine = (String) Vtype.getSelectedItem();
//        vaccine = StatusClass.vaccinename;
        try {
            int byear = Integer.parseInt(year.trim());
            int cyear = Calendar.getInstance().get(Calendar.YEAR);
            int age = cyear - byear;
            StatusClass.age = age;
        } catch (NumberFormatException nfe) {
            //            JOptionPane.showMessageDialog(this, nfe);
            nfe.printStackTrace();
        }
        if (idno.isEmpty()) {
            Messages.showWarning("Enter Id no", "Please enter");
        } else if (year.isEmpty()) {
            Messages.showWarning("Enter Id no", "Please enter");
        } else {
            ResultSet rs = db.getData("select * from regisetrforvaccine where PID='" + pid + "'");
            ResultSet rs4 = db.getData("select * from register_tbl where rid='" + pid + "'");
            try {
                if (rs.next() && rs4.next()) {
                    String ref = rs.getString(14);
                    String fname = rs4.getString(2);
                    String email = rs4.getString(4);
                    sendMail se = new sendMail();
                    JOptionPane.showMessageDialog(this, "Wait second");
                    String msg1 = "Ｈｅｌｌｏ  " + fname + "  Ｙｏｕｒ Ｖａｃｃｉｎａｔｉｏｎ ｉｓ Ｒｅｇｉｓｔｒａｔｉｏｎ ｉｓ ｃｏｍｐｌｅｔｅｄ  \n"
                            + "Ａｎｄ Ｙｏｕｒ Ｒｅｆｆｅｒｅｎｃｅ ｎｕｍｂｅｒ ｉｓ ：" + ref + "";
                    
                    se.sendMail(email, msg1, ref);
                    new RegistrationStatus().setVisible(true);
                } else {
                    
                    int age = StatusClass.age;
                    int a = age;
                    if (a >= 18) {
                        try {
                            PDFUtility pdf = new PDFUtility();
                            pdf.generatePdf(rand, ceter, time, name, vaccine, doseno, idtype, date);
//                            String qrCodeData = "Refference id: " + rand + "\n" + "first name: " + name + "Vaccination Center: " + ceter + " And Vaccination Date: " + date;
//                            String filePath = "C:\\Users\\Aditya\\Desktop\\Rutuja\\Covid19Vaccine\\src\\QR\\" + rand + ".png";
//                            String charset = "UTF-8"; // or "ISO-8859-1"
//                            Map< EncodeHintType, ErrorCorrectionLevel> hintMap = new HashMap< EncodeHintType, ErrorCorrectionLevel>();
//                            hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
//                            BitMatrix matrix = new MultiFormatWriter().encode(
//                                    new String(qrCodeData.getBytes(charset), charset),
//                                    BarcodeFormat.QR_CODE, 200, 200, hintMap);
//                            MatrixToImageWriter.writeToFile(matrix, filePath.substring(filePath
//                                    .lastIndexOf('.') + 1), new File(filePath));
//                            File f = new File("C:\\Users\\Aditya\\Desktop\\R````````utuja\\Covid19Vaccine\\src\\QR\\" + rand + ".png");
                        } catch (Exception e) {
                            System.err.println(e);
                        }
                        db.execute("Insert into regisetrforvaccine values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", id, idtype, idno, f, name, gender, age, year, date, ceter, vaccine, time, doseno, pid, rand);
                        JOptionPane.showMessageDialog(this, "Registration successfully\nVisite selected vaccination center on " + date);
                        if (rs4.next()) {
                            String email = rs4.getString(4);
                            String fname = rs4.getString(2);
                            sendMail se = new sendMail();
                            JOptionPane.showMessageDialog(this, "Wait second");
                            String msg = "Ｈｅｌｌｏ  " + fname + "  Ｙｏｕｒ Ｖａｃｃｉｎａｔｉｏｎ ｉｓ Ｒｅｇｉｓｔｒａｔｉｏｎ ｉｓ ｃｏｍｐｌｅｔｅｄ  \n"
                                    + "Ａｎｄ Ｙｏｕｒ Ｒｅｆｆｅｒｅｎｃｅ ｎｕｍｂｅｒ ｉｓ ：  " + rand + "";
                            se.sendMail(email, msg, rand);
                            dispose();
                            new RegistrationStatus().setVisible(true);
                        }
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "You are not eligible for vaccination");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegisterForVaccine.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(RegisterForVaccine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void VtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VtypeItemStateChanged

    }//GEN-LAST:event_VtypeItemStateChanged

    private void CenterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CenterItemStateChanged

    }//GEN-LAST:event_CenterItemStateChanged

    private void CenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenterActionPerformed
//        ResultSet rs = db.getData("select covaxin from centertbl where covaxin <= 100");
//        ResultSet rs1 = db.getData("select covishield from centertbl where covishield <= 100");
//        try {
//            if (rs.next()) {
//                
//            } else {
//                Vtype.addItem("Covaxin");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(RegisterForVaccine.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            if(rs1.next()){
//                
//            }else{
//                Vtype.addItem("Covishield");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(RegisterForVaccine.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_CenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BYear;
    private javax.swing.JComboBox<String> Center;
    private javax.swing.JComboBox<String> Cmbid1;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField IdNo;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox<String> Vtype;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JComboBox<String> time;
    // End of variables declaration//GEN-END:variables
}
