/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.covid.forms;

import com.covid.classes.DBClass;
import com.covid.classes.ImageUtiltiy;
import com.covid.classes.Messages;
import com.covid.classes.StatusClass;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.io.File;

/**
 *
 * @author Aditya
 */
public class RegistrationStatus extends javax.swing.JFrame {

    String pid = StatusClass.id;
    DBClass db = new DBClass();

    /**
     * Creates new form RegistrationStatus
     */
    public RegistrationStatus() {
        initComponents();
        String pid = StatusClass.id;
        ResultSet rs1 = db.getData("select * from regisetrforvaccine where pid='" + pid + "'");
        try {
            if (rs1.next()) {
                String vcname = rs1.getString(11);
                String rand = rs1.getString(15);
                String dose = rs1.getString(13);
                String Dtype = rs1.getString(2);
                this.Dtype.setText("Document Type: " + Dtype);
                Dose.setText("Vaccination Status: " + dose);
                File f = new File("C:\\Users\\Aditya\\Desktop\\Rutuja\\Covid19Vaccine\\src\\QR\\" + rand + ".png");
                ImageUtiltiy.setLabelImage(f, img);
                String vccenter = rs1.getString(10);
                String date = rs1.getString(9);
                String idno = rs1.getString(3);
                Date.setText("Vaccination Date: " + date);
                IDNo1.setText("Document Id: " + idno);
                CenterName.setText("Vaccination Center: " + vccenter);
                Vaccinenm.setText("Vaccine name: " + vcname);

            } else {
                Messages.showError("data does not exist", "Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        Vaccinenm = new javax.swing.JLabel();
        CenterName = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Dtype = new javax.swing.JLabel();
        Dose = new javax.swing.JLabel();
        IDNo1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 0, 102));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 153, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificate (3).png"))); // NOI18N
        jLabel6.setText("Vaccination Status");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(19, 19, 19))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        img.setBackground(new java.awt.Color(255, 0, 51));
        img.setOpaque(true);
        kGradientPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 88, 148, 150));

        Vaccinenm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Vaccinenm.setForeground(new java.awt.Color(255, 255, 255));
        Vaccinenm.setText("Vaccine Name");
        kGradientPanel1.add(Vaccinenm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        CenterName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CenterName.setForeground(new java.awt.Color(255, 255, 255));
        CenterName.setText("Center Name");
        kGradientPanel1.add(CenterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        kGradientPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        Dtype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Dtype.setForeground(new java.awt.Color(255, 255, 255));
        Dtype.setText("Document type");
        kGradientPanel1.add(Dtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        Dose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Dose.setForeground(new java.awt.Color(255, 255, 255));
        Dose.setText("Date");
        kGradientPanel1.add(Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        IDNo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IDNo1.setForeground(new java.awt.Color(255, 255, 255));
        IDNo1.setText("Id No");
        kGradientPanel1.add(IDNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jButton1.setText("Cancel Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        jButton2.setText("Reshedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = Messages.showConfirm("Do you want to delete?", "Confirm");
        if (i == JOptionPane.YES_OPTION) {
            db.execute("delete from regisetrforvaccine where pid='5'");
            dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new RegisterForVaccine().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CenterName;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Dose;
    private javax.swing.JLabel Dtype;
    private javax.swing.JLabel IDNo1;
    private javax.swing.JLabel Vaccinenm;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
